sudo: required
services:
    - docker
    
before_install:
    - docker build -t Shriya/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true Shriya/docker-react npm run test
language: generic